### ISSUE TITLE
parse部のバグ修正

### ISSUE THREAD

**Issue by wkodate** [wkodate/Jupiter-rss2db#8]
```
$ tail -f /tmp/rss2db_web.log
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 19: 要素タイプ"img"は、対応する終了タグ"</img>"で終了する必要があります。
    at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:198)
    at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:123)
    at com.wkodate.jupiter.rss2db.rss.RssParser.<init>(RssParser.java:31)
    at com.wkodate.jupiter.rss2db.rss.RssParserThread.call(RssParserThread.java:35)
    at com.wkodate.jupiter.rss2db.rss.RssParserThread.call(RssParserThread.java:17)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.jdom.input.JDOMParseException: Error on line 19: 要素タイプ"img"は、対応する終了タグ"</img>"で終了する必要があります。
    at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
    at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
    at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:194)
    ... 8 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 19; columnNumber: 6; 要素タイプ"img"は、対応する終了タグ"</img>"で終了する必要があります。
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1438)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1750)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
    ... 10 more
```

**Comment by wkodate** [comment]
duplicate #12
