### ISSUE TITLE
SQL失敗時のスキップ処理追加

### ISSUE THREAD

**Issue by wkodate** [wkodate/Jupiter-rss2db#9]
まとめてinsertする部分でMySQLSyntaxErrorException

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Ï‰`)ï¾”ï½±(*^â—¯^*)ã�„ã�¤ã‚‚ã�®ãƒ¡ãƒ³ãƒ�ãƒ¼ã�ªã‚“ã�
2: ...', '2016-06-13 00:08' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1541)
        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2605)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1469)
        at com.wkodate.jupiter.rss2db.db.MySqlClient.insert(MySqlClient.java:33)
        at com.wkodate.jupiter.rss2db.RssToDb.process(RssToDb.java:89)
        at com.wkodate.jupiter.rss2db.RssToDb.main(RssToDb.java:135)
```

**Comment by wkodate** [comment]
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Ï‰'*)
...', '2016-06-17 21:23:35', 'http://livedoor.blogimg.jp/bmaysu/imgs/3/7/3' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1541)
        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2605)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1469)
        at com.wkodate.jupiter.rss2db.db.MySqlClient.insert(MySqlClient.java:33)
        at com.wkodate.jupiter.rss2db.RssToDb.process(RssToDb.java:92)
        at com.wkodate.jupiter.rss2db.RssToDb.main(RssToDb.java:143)
```
